### ISSUE TITLE
Add identity of CStorPoolCluster in CStor cluster config 

### ISSUE THREAD

**Issue by shovanmaity** [mayadata-io/cstorpoolauto#104]
CStorPool cluster identity is not present in CStor cluster config it will help us to clean up the associated resource.

**Comment by AmitKumarDas** [comment]
@shovanmaity I guess "dao.mayadata.io/cstorclusterconfig-uid" should be present in CStorPoolCluster annotations.

**Comment by shovanmaity** [comment]
Yes, it is present. Thanks.

**Comment by AmitKumarDas** [comment]
I will add another one in addition to above:
```yaml
annotations:
 dao.mayadata.io/cstorclusterconfig-localdisk: "true"
```

**Comment by AmitKumarDas** [comment]
PR #107
